name: Test Build Tools
description: testing

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        
      - name: install build tools
        uses: rhattox-shared-actions/shared-actions/actions/tools@main